---
- name: Create /etc/dconf/profile/user
  template:
    src: user.j2
    dest: /etc/dconf/profile/user
    mode: '0644'

- name: Check /etc/dconf/db
  file:
    path: /etc/dconf/db
    state: directory
    recurse: yes
    mode: '0755'
    owner: root
    group: root

- name: Create /etc/dconf/db/local.d/00-all
  template:
    src: 00-all.j2
    dest: /etc/dconf/db/local.d/00-all
  register: dconf_all

- name: Update dconf
  command: dconf update
  environment:
    DISPLAY: ":0"
  when: dconf_all.changed == true
