---
# - name: Install Mailspring
#   snap:
#     name:
#       - mailspring
- name: Check if mailspring is installed
  command: rpm -qa mailspring
  register: mailspring
  changed_when: False
  failed_when: False
  args:
    warn: false

- name: Install Mailspring
  dnf:
    name: https://updates.getmailspring.com/download?platform=linuxRpm
    state: present
  when: (mailspring.stdout == "")
