---
# - name: Install Mailspring
#   snap:
#     name:
#       - mailspring
- name: Check if mailspring is installed
  command: rpm -qa mailspring
  register: mailspring
  changed_when: False
  failed_when: False
  args:
    warn: false

- name: Download mailspring
  get_url:
    url: https://updates.getmailspring.com/download?platform=linuxRpm
    dest: /tmp/mailspring.rpm
  when: (mailspring.stdout == "")

- name: Install Mailspring
  dnf:
    name: /tmp/mailspring.rpm
    state: present
  when: (mailspring.stdout == "")

- name: Remove Mailspring rpm
  file:
    path: /tmp/mailspring.rpm
    state: absent
  when: (mailspring.stdout == "")
