---
- name: Copy default wallpaper
  command: cp --no-preserve=mode,ownership /var/lib/ansible-workstation-assets/wallpaper/{{ wallpaper }}/{{ wallpaper }}.jpg /usr/share/backgrounds/{{ wallpaper }}.jpg
  when: (wallpaper != "")
  args:
    creates: "/usr/share/backgrounds/{{ wallpaper }}.jpg"

- name: Update wallpaper permissions
  file:
    path: "/usr/share/backgrounds/{{ wallpaper }}.jpg"
    state: file
    mode: '0644'
    owner: root
    group: root
  when: (wallpaper != "")

- name: Create /etc/dconf/db/local.d/01-wallpaper
  template:
    src: 01-wallpaper.j2
    dest: /etc/dconf/db/local.d/01-wallpaper
  register: dconf_wallpaper
  when: (wallpaper != "")

- name: Update dconf
  command: dconf update
  environment:
    DISPLAY: ":0"
  when: dconf_wallpaper.changed == true

- name: Add flat-remix repository
  command: "dnf copr enable daniruiz/flat-remix -y"
  args:
    creates: "/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:daniruiz:flat-remix.repo"
    warn: false

- name: Check if flat-remix-gtk is installed
  command: rpm -qa flat-remix-gtk
  register: flat_remix_gtk
  changed_when: False
  failed_when: False
  args:
    warn: false

- name: Install flat-remix-gtk
  dnf:
    name: flat-remix-gtk
    state: present
  when: (flat_remix_gtk.stdout == "")

- name: Check if flat-remix-gnome is installed
  command: rpm -qa flat-remix-gnome
  register: flat_remix_gnome
  changed_when: False
  failed_when: False
  args:
    warn: false

- name: Install flat-remix-gnome
  dnf:
    name: flat-remix-gnome
    state: present
  when: (flat_remix_gnome.stdout == "")

- name: Check if flat-remix is installed
  command: rpm -qa flat-remix
  register: flat_remix
  changed_when: False
  failed_when: False
  args:
    warn: false

- name: Install flat-remix
  dnf:
    name: flat-remix
    state: present
  when: (flat_remix.stdout == "")

# - name: Install glib2-devel
#   dnf:
#     name: glib2-devel
#     state: present

# - name: Install ImageMagick
#   dnf:
#     name: ImageMagick
#     state: present

# - name: Check flat-remix-gnome
#   stat:
#     path: /var/lib/flat-remix-gnome
#   register: flat_remix_gnome

# - name: Clone flat-remix-gnome
#   shell: git clone https://github.com/daniruiz/flat-remix-gnome.git /var/lib/flat-remix-gnome
#   changed_when: False
#   when: ((flat_remix_gnome.stat.isdir is defined and flat_remix_gnome.stat.isdir) == False)

# - name: Pull flat-remix-gnome
#   shell: cd /var/lib/flat-remix-gnome && git reset --hard && git pull
#   changed_when: False
#   when: (flat_remix_gnome.stat.isdir is defined and flat_remix_gnome.stat.isdir)

# - name: Update /var/lib/flat-remix-gnome permissions
#   file:
#     path: /var/lib/flat-remix-gnome
#     state: directory
#     recurse: yes
#     mode: '0755'
#     owner: root
#     group: root

- name: Create /etc/dconf/db/local.d/01-all
  template:
    src: 01-all.j2
    dest: /etc/dconf/db/local.d/01-all
  register: dconf_all2

- name: Update dconf
  command: dconf update
  environment:
    DISPLAY: ":0"
  when: dconf_all2.changed == true
