---
- name: Check if google-chrome-stable is installed
  command: rpm -qa google-chrome-stable
  register: google_chrome_stable
  changed_when: False
  failed_when: False
  args:
    warn: false

- name: Install Google Chrome
  dnf:
    name: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    state: present
  when: (google_chrome_stable.stdout == "")
