---
- name: Get Fedora release number
  shell: source /etc/os-release && echo ${VERSION_ID}
  register: os_release
  changed_when: False
  failed_when: False

- name: Install git
  dnf:
    name: git
    state: present

- name: Clone ansible-workstation-assets
  git:
    repo: 'https://github.com/shawnallen85/ansible-workstation-assets.git'
    dest: /var/lib/ansible-workstation-assets
    update: yes
  changed_when: False

- name: Install gnome-tweak-tool
  dnf:
    name: gnome-tweak-tool
    state: present

- name: Install gnome-shell-extensions
  dnf:
    name: "{{ gnome_shell_extensions }}"
    state: present

- name: Install flatpak
  dnf:
    name: flatpak
    state: present
  register: flatpak

- name: Add Flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  when: flatpak.msg is search("Installed")

- name: Upgrade all packages to the latest version
  dnf:
    name: "*"
    state: latest
