---
- name: Add manuelschneid3r key
  shell: rpm --import https://build.opensuse.org/projects/home:manuelschneid3r/public_key
  args:
    warn: false

- name: Add manuelschneid3r repository
  shell: dnf config-manager --add-repo https://download.opensuse.org/repositories/home:manuelschneid3r/Fedora_{{ os_release.stdout }}/home:manuelschneid3r.repo
  args:
    warn: false

- name: Check if albert is installed
  command: rpm -qa albert
  register: albert
  changed_when: False
  failed_when: False
  args:
    warn: false

- name: Install albert
  dnf:
    name: albert
    state: present
  when: (albert.stdout == "")

- name: Create /etc/xdg/autostart/albert.desktop
  template:
    src: autostart.j2
    dest: /etc/xdg/autostart/albert.desktop
    mode: '0644'
